<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.7</version>
    </parent>

    <groupId>com.bricklink.api</groupId>
    <artifactId>bricklink-rest</artifactId>
    <version>2.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>Bricklink API :: REST</name>

    <modules>
        <module>bricklink-model</module>
        <module>bricklink-rest-client</module>
        <module>bricklink-spring-boot-starter</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>21</java.version>
        <lombok.version>1.18.46</lombok.version>
        <maven-compiler-plugin.version>3.14.1</maven-compiler-plugin.version>
        <wiremock.version>3.13.2</wiremock.version>
        <github.organization>LegoHunter</github.organization>
        <github.repo.url>https://maven.pkg.github.com/${github.organization}/bricklink-rest</github.repo.url>
    </properties>

    <distributionManagement>
        <repository>
            <id>github</id>
            <name>GitHub Packages</name>
            <url>${github.repo.url}</url>
        </repository>
    </distributionManagement>

    <repositories>
        <repository>
            <id>central</id>
            <url>https://repo1.maven.org/maven2</url>
        </repository>
        <repository>
            <id>github</id>
            <url>https://maven.pkg.github.com/${github.organization}/*</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.bricklink.api</groupId>
                <artifactId>bricklink-model</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.bricklink.api</groupId>
                <artifactId>bricklink-rest-client</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <configuration>
                        <release>${java.version}</release>
                        <annotationProcessorPaths>
                            <path>
                                <groupId>org.projectlombok</groupId>
                                <artifactId>lombok</artifactId>
                                <version>${lombok.version}</version>
                            </path>
                            <path>
                                <groupId>org.springframework.boot</groupId>
                                <artifactId>spring-boot-configuration-processor</artifactId>
                            </path>
                        </annotationProcessorPaths>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.openrewrite.maven</groupId>
                    <artifactId>rewrite-maven-plugin</artifactId>
                    <version>6.22.1</version>
                    <configuration>
                        <activeRecipes>
                            <recipe>org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_0</recipe>
                            <recipe>org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_1</recipe>
                            <recipe>org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_2</recipe>
                            <recipe>org.openrewrite.java.spring.boot3.SpringBootProperties_3_3</recipe>
                            <recipe>org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_3</recipe>
                            <recipe>org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_4</recipe>
                            <recipe>org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_5</recipe>
                        </activeRecipes>
                    </configuration>
                    <dependencies>
                        <dependency>
                            <groupId>org.openrewrite.recipe</groupId>
                            <artifactId>rewrite-spring</artifactId>
                            <version>6.17.0</version>
                        </dependency>
                    </dependencies>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
